CC := gcc
CFLAGS := -Wall -pedantic -std=c23 -g -fsanitize=address

ej1: ej1.c
	$(CC) $(CFLAGS) ej1.c -o ej1

ej2: ej2.c
	$(CC) $(CFLAGS) ej2.c -o ej2

ej3: ej3.c
	$(CC) $(CFLAGS) ej3.c -o ej3

clean:
	rm ej1 ej2 ej3
