CC := gcc
CFLAGS := -Wall -Wextra -pedantic -std=c23 -g

ej10: ej10.c
	$(CC) $(CFLAGS) ej10.c -o ej10

ej15: ej15.c
	$(CC) $(CFLAGS) ej15.c -o ej15

ej16: ej16.c
	$(CC) $(CFLAGS) ej16.c -o ej16

ej18: ej18.c
	$(CC) $(CFLAGS) ej18.c -o ej18
